"""initial schema

Revision ID: 9ee4541e3057
Revises: 
Create Date: 2026-09-16 20:43:57.364726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee4541e3057'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vm_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('glpi_ticket_id', sa.String(length=64), nullable=True),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=True),
    sa.Column('vlan', sa.String(length=64), nullable=True),
    sa.Column('cpu', sa.Integer(), nullable=True),
    sa.Column('ram_gb', sa.Integer(), nullable=True),
    sa.Column('disk_gb', sa.Integer(), nullable=True),
    sa.Column('os_template', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ip_reserved', 'provisioning', 'post_install', 'done', 'failed', name='request_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vm_requests')
    # ### end Alembic commands ###
