"""add netmask and gateway to vm_requests

Revision ID: fee76afa014c
Revises: 1b9b547abf91
Create Date: 2026-09-29 08:36:37.382447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee76afa014c'
down_revision: Union[str, None] = '1b9b547abf91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vm_requests', sa.Column('netmask', sa.String(length=8), nullable=True))
    op.add_column('vm_requests', sa.Column('gateway', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vm_requests', 'gateway')
    op.drop_column('vm_requests', 'netmask')
    # ### end Alembic commands ###
